apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: tk2w011kr-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/tk2w011kr-java-springboot-gitops